### ISSUE TITLE
'missing configuration' error

### ISSUE THREAD

**Issue by avsaponchik** [flawsv/apb#2]
with an update from 18.08.2024 when you start the game using the APB.exe (with your parameters, but not using the regular Launcher.exe) you get this error.
perhabs, new anticheat requires more launch options.
anyone figured out what those are?

**Comment by Danishbjoe** [comment]
it happens whit advanced launcher as well

**Comment by flawsv** [comment]
This issue was not caused by my config but by a recent hotfix deployed by little orbit themselves which broke launching the game through the APB.exe. They've already addressed and solved the issue with _another_ hotfix shortly after.

Simply update the game again and apply the configs then start the game through your APB.exe shortcut as usual.
